layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:
  ( dmy0                      0          dmy0         )
  ( dmy1                      1          dmy1         )
  ( dmy2                      2          dmy2         )
  ( dmy3                      3          dmy3         )
  ( dmy4                      4          dmy4         )
  ( dmy5                      5          dmy5         )
  ( dmy6                      6          dmy6         )
  ( dmy7                      7          dmy7         )
  ( dmy8                      8          dmy8         )
  ( dmy9                      9          dmy9         )
  ( marking                   17                      )  ; GDS data type 17
  ( waterMark                 63         waterMark    )
  ( dummy                     127        dummy        )
  ( subnode                   221        subnode      )
  ( extract                   222        extract      )
 ;System-Reserved Purposes:
  ( redundant                 -8         red          )
  ( gapFill                   -7         gap          )
  ( annotation                -6         ann          )
  ( OPCAntiSerif              -5         opa          )
  ( OPCSerif                  -4         ops          )
  ( slot                      -3         slt          )
  ( fill                      -2         fil          )
  ( drawing                   -1         drw          )
  ( fatal                     223        fat          )
  ( critical                  224        crt          )
  ( soCritical                225        scr          )
  ( soError                   226        ser          )
  ( ackWarn                   227        ack          )
  ( info                      228        inf          )
  ( track                     229        trk          )
  ( blockage                  230        blk          )
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes

 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( COMP                      22         COMP         )
  ( DNWELL                    12         DNWELL       )
  ( Nwell                     21         Nwell        )
  ( LVPWELL                   2040       LVPWELL      )  ; GDS num 204 conflicts with sys reserved num
  ( Dualgate                  55         Dualgate     )
  ( Poly2                     30         Poly2        )
  ( Nplus                     32         Nplus        )
  ( Pplus                     31         Pplus        )
  ( SAB                       49         SAB          )
  ( ESD                       24         ESD          )
  ( Contact                   33         Contact      )
  ( Metal1                    34         Metal1       )
  ( Via1                      35         Via1         )
  ( Metal2                    36         Metal2       )
  ( Via2                      38         Via2         )
  ( Metal3                    42         Metal3       )
  ( Via3                      40         Via3         )
  ( Metal4                    46         Metal4       )
  ( Via4                      41         Via4         )
  ( Metal5                    81         Metal5       )
  ( Via5                      82         Via5         )
  ( MetalTop                  53         MetalTop     )
  ( Pad                       37         Pad          )
  ( Resistor                  62         Resistor     )
  ( FHRES                     2270       FHRES        )  ; GDS num 227 conflicts with sys reserved num
  ( FuseWindow_D              96         FuseWindow_D )
  ( POLYFUSE                  2200       POLYFUSE     )  ; GDS num 220 conflicts with sys reserved num
  ( MVSD                      2100       MVSD         )  ; GDS num 210 conflicts with sys reserved num
  ( MVPSD                     11         MVPSD        )
  ( NAT                       5          NAT          )
  ( UBMPPeri                  183        UBMPPeri     )
  ( UBMPArray                 184        UBMPArray    )
  ( UBMEPlate                 185        UBMEPlate    )
  ( Schottky_diode            241        Schottky_diode )
  ( ZENER                     178        ZENER        )
  ( RES_MK                    110        RES_MK       )
  ( OPC_drc                   124        OPC_drc      )
  ( NDMY                      111        NDMY         )
  ( PMNDMY                    152        PMNDMY       )
  ( V5_XTOR                   112        V5_XTOR      )
  ( CAP_MK                    117        CAP_MK       )
  ( MOS_CAP_MK                166        MOS_CAP_MK   )
  ( IND_MK                    151        IND_MK       )
  ( DIODE_MK                  115        DIODE_MK     )
  ( DRC_BJT                   127        DRC_BJT      )
  ( LVS_BJT                   118        LVS_BJT      )
  ( MIM_L_MK                  11710      MIM_L_MK     )  ; GDS num 117; data type 10
  ( Latchup_MK                137        Latchup_MK   )
  ( GUARD_RING_MK             167        GUARD_RING_MK )
  ( OTP_MK                    173        OTP_MK       )
  ( MTPMARK                   122        MTPMARK      )
  ( NEO_EE_MK                 88         NEO_EE_MK    )
  ( SramCore                  108        SramCore     )
  ( LVS_RF                    100        LVS_RF       )
  ( LVS_Drain                 1007       LVS_Drain    )  ; GDS num 100; data type 7
  ( HVPOLYRS                  123        HVPOLYRS     )  ; GDS
  ( LVS_IO                    119        LVS_IO       )
  ( PROBE_MK                  13         PROBE_MK     )
  ( ESD_MK                    2405       ESD_MK       )  ; GDS num 24; data type 05
  ( LVS_Source                1008       LVS_Source   )  ; GDS num 100; data type 8
  ( WELL_DIODE_MK             153        WELL_DIODE_MK )
  ( LDMOS_XTOR                2260       LDMOS_XTOR   )  ; GDS num 226 conflicts with sys reserved num
  ( PLFUSE                    125        PLFUSE       )
  ( EFUSE_MK                  80         EFUSE_MK     )
  ( MCELL_FEOL_MK             1113      MCELL_FEOL_MK )  ; GDS num 11; data type 17
  ( YMTP_MK                   86         YMTP_MK      )
  ( DEV_WF_MK                 128        DEV_WF_MK    )
  ( PR_bndry                  0          PR_bndry     )
  ( MDIODE                    116        MDIODE       )
  ( Border                    63         Border       )
 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        noOcupy      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFnc      )
  ( softFence                 206        softFnc      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        dsnFlow      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLyr      )
  ( changedLayer              220        chngLyr      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBndry      )
  ( instance                  236        instnce      )
  ( annotate                  237        anotate      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( substrate                 240        substrate    )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( NDMY                      blockage   )
  ( PMNDMY                    blockage   )
  ( Nwell                     subnode    )
  ( COMP                      subnode    )
  ( Poly2                     subnode    )
  ( Contact                   subnode    )
  ( Nplus                     subnode    )
  ( Pplus                     subnode    )
  ( Metal1                    subnode    )
  ( Via1                      subnode    )
  ( Metal2                    subnode    )
  ( Via2                      subnode    )
  ( Metal3                    subnode    )
  ( Via3                      subnode    )
  ( Metal4                    subnode    )
  ( Via4                      subnode    )
  ( Metal5                    subnode    )
  ( Via5                      subnode    )
  ( MetalTop                  subnode    )
  ( LVPWELL                   drawing    )
  ( LVPWELL                   subnode    )
  ( DNWELL                    drawing    )
  ( Nwell                     drawing    )
  ( Nwell                     net        )
  ( COMP                      drawing    )
  ( COMP                      net        )
  ( Pplus                     drawing    )
  ( Pplus                     net        )
  ( Nplus                     drawing    )
  ( Nplus                     net        )
  ( NAT                       drawing    )
  ( Poly2                     drawing    )
  ( Poly2                     net        )
  ( Poly2                     pin        )
  ( Contact                   drawing    )
  ( Contact                   net        )
  ( Metal1                    drawing    )
  ( Metal1                    net        )
  ( Metal1                    pin        )
  ( Via1                      drawing    )
  ( Via1                      net        )
  ( Metal2                    drawing    )
  ( Metal2                    net        )
  ( Metal2                    pin        )
  ( Via2                      drawing    )
  ( Via2                      net        )
  ( Metal3                    drawing    )
  ( Metal3                    net        )
  ( Metal3                    pin        )
  ( Via3                      drawing    )
  ( Via3                      net        )
  ( Metal4                    drawing    )
  ( Metal4                    net        )
  ( Metal4                    pin        )
  ( Via4                      drawing    )
  ( Via4                      net        )
  ( Metal5                    drawing    )
  ( Metal5                    net        )
  ( Metal5                    pin        )
  ( Via5                      drawing    )
  ( Via5                      net        )
  ( MetalTop                  drawing    )
  ( MetalTop                  net        )
  ( MetalTop                  pin        )
  ( COMP                      dummy      )
  ( Poly2                     dummy      )
  ( Metal1                    dummy      )
  ( Metal2                    dummy      )
  ( Metal3                    dummy      )
  ( Metal4                    dummy      )
  ( Metal5                    dummy      )
  ( MetalTop                  dummy      )
  ( Metal1                    blockage   )
  ( Metal2                    blockage   )
  ( Metal3                    blockage   )
  ( Metal4                    blockage   )
  ( Metal5                    blockage   )
  ( Metal1                    slot       )
  ( Metal2                    slot       )
  ( Metal3                    slot       )
  ( Metal4                    slot       )
  ( Metal5                    slot       )
  ( MetalTop                  slot       )
  ( Contact                   boundary   )
  ( Via1                      boundary   )
  ( Via2                      boundary   )
  ( Via3                      boundary   )
  ( Via4                      boundary   )
  ( Via5                      boundary   )
  ( Metal1                    boundary   )
  ( Metal2                    boundary   )
  ( Metal3                    boundary   )
  ( Metal4                    boundary   )
  ( Metal5                    boundary   )
  ( MetalTop                  boundary   )
  ( RES_MK                    drawing    )
  ( Resistor                  drawing    )
  ( IND_MK                    drawing    )
  ( DRC_BJT                   drawing    )
  ( LVS_BJT                   drawing    )
  ( DIODE_MK                  drawing    )
  ( Metal1                    label      )
  ( Metal2                    label      )
  ( Metal3                    label      )
  ( Metal4                    label      )
  ( Metal5                    label      )
  ( MetalTop                  label      )
  ( Poly2                     label      )
  ( Dualgate                  drawing    )
  ( SAB                       drawing    )
  ( ESD                       drawing    )
  ( Pad                       drawing    )
  ( FHRES                     drawing    )
  ( FuseWindow_D              drawing    )
  ( POLYFUSE                  drawing    )
  ( MVSD                      drawing    )
  ( MVPSD                     drawing    )
  ( COMP                      dummy      )
  ( Poly2                     dummy      )
  ( COMP                      label      )
  ( UBMPPeri                  drawing    )
  ( UBMPArray                 drawing    )
  ( UBMEPlate                 drawing    )
  ( Schottky_diode            drawing    )
  ( ZENER                     drawing    )
  ( OPC_drc                   drawing    )
  ( V5_XTOR                   drawing    )
  ( CAP_MK                    drawing    )
  ( MOS_CAP_MK                drawing    )
  ( MIM_L_MK                  drawing    )
  ( Latchup_MK                drawing    )
  ( GUARD_RING_MK             drawing    )
  ( OTP_MK                    drawing    )
  ( MTPMARK                   drawing    )
  ( NEO_EE_MK                 drawing    )
  ( SramCore                  drawing    )
  ( LVS_RF                    drawing    )
  ( LVS_Drain                 drawing    )
  ( HVPOLYRS                  drawing    )
  ( LVS_IO                    drawing    )
  ( PROBE_MK                  drawing    )
  ( ESD_MK                    drawing    )
  ( LVS_Source                drawing    )
  ( WELL_DIODE_MK             drawing    )
  ( LDMOS_XTOR                drawing    )
  ( PLFUSE                    drawing    )
  ( EFUSE_MK                  drawing    )
  ( MCELL_FEOL_MK             drawing    )
  ( YMTP_MK                   drawing    )
  ( DEV_WF_MK                 drawing    )
  ( MDIODE                    drawing    )
  ( Border                    drawing    )
  ( PR_bndry                  boundary   )

  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( border                    boundary   )
  ( device                    drawing    )
  ( device                    label      )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      drawing    )
  ( snap                      boundary   )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( y0                        flight     )
  ( y1                        flight     )
  ( y2                        flight     )
  ( y3                        flight     )
  ( y4                        flight     )
  ( y5                        flight     )
  ( y6                        flight     )
  ( y7                        flight     )
  ( y8                        flight     )
  ( y9                        flight     )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( marker                    annotate   )
  ( marker                    info       )
  ( marker                    ackWarn    )
  ( marker                    soError    )
  ( marker                    soCritical )
  ( marker                    critical   )
  ( marker                    fatal      )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Row                       boundary   )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Group                     boundary   )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( Unrouted                  track      )


 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )

  ( background   drawing      background       t nil t nil nil )
  ( grid         drawing      grid             t nil t nil nil )
  ( grid         drawing1     grid1            t nil t nil nil )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        nil t t t nil )
  ( instance     drawing      instance         t t t t nil )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t t t t nil )
  ( prBoundary   boundary     prBoundaryBnd    t t t t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( align        drawing      align            t t t t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )

  ( DNWELL       drawing      dnw              t t nil t t )
  ( Nwell        drawing      nwell            t t nil t t )
  ( COMP         drawing      sldiff           t t nil t t )
  ( NAT          drawing      nat              t t nil t t )
  ( Poly2        drawing      poly             t t nil t t )
  ( Poly2        pin          polyPin          t t t   t t )
  ( Pplus        drawing      pplus            t t nil t t )
  ( Nplus        drawing      nplus            t t nil t t )
  ( Resistor     drawing      rpoly            t t nil t t )
  ( Contact      drawing      cont             t t nil t t )
  ( Contact      boundary     contb            t t nil t t )
  ( Metal1       drawing      m1               t t nil t t )
  ( Via1         drawing      v1               t t nil t t )
  ( Metal2       drawing      m2               t t nil t t )
  ( Via2         drawing      v2               t t nil t t )
  ( Metal3       drawing      m3               t t nil t t )
  ( Via3         drawing      v3               t t nil t t )
  ( Metal4       drawing      m4               t t nil t t )
  ( Via4         drawing      v4               t t nil t t )
  ( Metal5       drawing      m5               t t nil t t )
  ( Via5         drawing      v5               t t nil t t )
  ( MetalTop     drawing      m6               t t nil t t )
  ( LVPWELL      drawing      psub             t t nil t t )
  ( LVPWELL      subnode      psub             t t nil t t )
  ( Metal1       pin          m1Pin            t t nil t t )
  ( Metal2       pin          m2Pin            t t nil t t )
  ( Metal3       pin          m3Pin            t t nil t t )
  ( Metal4       pin          m4Pin            t t nil t t )
  ( Metal5       pin          m5Pin            t t nil t t )
  ( MetalTop     pin          m6Pin            t t nil t t )
  ( Metal1       blockage     m1Blk            t t nil t t )
  ( Metal2       blockage     m2Blk            t t nil t t )
  ( Metal3       blockage     m3Blk            t t nil t t )
  ( Metal4       blockage     m4Blk            t t nil t t )
  ( Metal5       blockage     m5Blk            t t nil t t )
  ( MetalTop     blockage     m6Blk            t t nil t t )
  ( Metal1       boundary     m1b              t t nil t nil )
  ( Metal2       boundary     m2b              t t nil t nil )
  ( Metal3       boundary     m3b              t t nil t nil )
  ( Metal4       boundary     m4b              t t nil t nil )
  ( Metal5       boundary     m5b              t t nil t nil )
  ( MetalTop     boundary     m6b              t t nil t nil )
  ( Via1         boundary     v1b              t t nil t nil )
  ( Via2         boundary     v2b              t t nil t nil )
  ( Via3         boundary     v3b              t t nil t nil )
  ( Via4         boundary     v4b              t t nil t nil )
  ( Via5         boundary     v5b              t t nil t nil )
  ( IND_MK       drawing      inddmy           t t nil t t )
  ( DRC_BJT      drawing      bjtdummy         t t nil t t )
  ( LVS_BJT      drawing      LVS_BJT          t t nil t t )
  ( DIODE_MK     drawing      diode            t t nil t t )
  ( NDMY         blockage     exclude          t t nil t t )
  ( PMNDMY       blockage     PMNDMY           t t nil t t )
  ( COMP         dummy        diffDmy          t t nil t t )
  ( Poly2        dummy        polyDmy          t t nil t t )
  ( Metal1       dummy        m1Pin            t t nil t t )
  ( Metal2       dummy        m2Pin            t t nil t t )
  ( Metal3       dummy        m3Pin            t t nil t t )
  ( Metal4       dummy        m4Pin            t t nil t t )
  ( Metal5       dummy        m5Pin            t t nil t t )
  ( MetalTop     dummy        m6Pin            t t nil t t )
  ( Metal1       slot         m1slot           t t nil t t )
  ( Metal2       slot         m2slot           t t nil t t )
  ( Metal3       slot         m3slot           t t nil t t )
  ( Metal4       slot         m4slot           t t nil t t )
  ( Metal5       slot         m5slot           t t nil t t )
  ( MetalTop     slot         m6slot           t t nil t t )
  ( Metal1       label        m1txt            t t nil t t )
  ( Metal2       label        m2txt            t t nil t t )
  ( Metal3       label        m3txt            t t nil t t )
  ( Metal4       label        m4txt            t t nil t t )
  ( Metal5       label        m5txt            t t nil t t )
  ( MetalTop     label        m6txt            t t nil t t )
  ( Poly2        label        polytxt          t t nil t t )

  ( Dualgate       drawing      Dualgate        t t nil t t )
  ( SAB            drawing      SAB             t t nil t t )
  ( ESD            drawing      ESD             t t nil t t )
  ( Pad            drawing      Pad             t t nil t t )
  ( FHRES          drawing      FHRES           t t nil t t )
  ( FuseWindow_D   drawing      FuseWindow_D    t t nil t t )
  ( POLYFUSE       drawing      POLYFUSE        t t nil t t )
  ( MVSD           drawing      MVSD            t t nil t t )
  ( MVPSD          drawing      MVPSD           t t nil t t )
  ( COMP           dummy        COMP_Dummy      t t nil t t )
  ( Poly2          dummy        Poly2_Dummy     t t nil t t )
  ( COMP           label        COMP_Label      t t nil t t )
  ( UBMPPeri       drawing      UBMPPeri        t t nil t t )
  ( UBMPArray      drawing      UBMPArray       t t nil t t )
  ( UBMEPlate      drawing      UBMEPlate       t t nil t t )
  ( Schottky_diode drawing      Schottky_diode  t t nil t t )
  ( ZENER          drawing      ZENER           t t nil t t )
  ( RES_MK         drawing      RES_MK          t t nil t t )
  ( OPC_drc        drawing      OPC_drc         t t nil t t )
  ( V5_XTOR        drawing      V5_XTOR         t t nil t t )
  ( CAP_MK         drawing      CAP_MK          t t nil t t )
  ( MOS_CAP_MK     drawing      MOS_CAP_MK      t t nil t t )
  ( MIM_L_MK       drawing      MIM_L_MK        t t nil t t )
  ( Latchup_MK     drawing      Latchup_MK      t t nil t t )
  ( GUARD_RING_MK  drawing      GUARD_RING_MK   t t nil t t )
  ( OTP_MK         drawing      OTP_MK          t t nil t t )
  ( MTPMARK        drawing      MTPMARK         t t nil t t )
  ( NEO_EE_MK      drawing      NEO_EE_MK       t t nil t t )
  ( SramCore       drawing      SramCore        t t nil t t )
  ( LVS_RF         drawing      LVS_RF          t t nil t t )
  ( LVS_Drain      drawing      LVS_Drain       t t nil t t )
  ( HVPOLYRS       drawing      HVPOLYRS        t t nil t t )
  ( LVS_IO         drawing      LVS_IO          t t nil t t )
  ( PROBE_MK       drawing      PROBE_MK        t t nil t t )
  ( ESD_MK         drawing      ESD_MK          t t nil t t )
  ( LVS_Source     drawing      LVS_Source      t t nil t t )
  ( WELL_DIODE_MK  drawing      WELL_DIODE_MK   t t nil t t )
  ( LDMOS_XTOR     drawing      LDMOS_XTOR      t t nil t t )
  ( PLFUSE         drawing      PLFUSE          t t nil t t )
  ( EFUSE_MK       drawing      EFUSE_MK        t t nil t t )
  ( MCELL_FEOL_MK  drawing      MCELL_FEOL_MK   t t nil t t )
  ( YMTP_MK        drawing      YMTP_MK         t t nil t t )
  ( DEV_WF_MK      drawing      DEV_WF_MK       t t nil t t )
  ( MDIODE         drawing      MDIODE          t t nil t t )
  ( Border         drawing      Border          t t nil t t )
  ( PR_bndry       boundary     PR_bndry        t t nil t t )
  ( LVS_BJT        drawing      LVS_BJT         t t nil t t )
  ( PMNDMY         blockage     PMNDMY          t t nil t t )

  ( text         drawing      text             t t t t t )
  ( text         drawing1     text1            t t t t nil )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( device       drawing1     device1          t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t t t t nil )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t nil )
  ( edgeLayer    drawing      edgeLayer        t t t t nil )
  ( edgeLayer    pin          edgeLayerPin     t t t t nil )
  ( snap         drawing      snap             t t t t nil )
  ( stretch      drawing      stretch          t t t t nil )
  ( y0           drawing      y0               t t t t nil )
  ( y1           drawing      y1               t t t t nil )
  ( y2           drawing      y2               t t t t nil )
  ( y3           drawing      y3               t t t t nil )
  ( y4           drawing      y4               t t t t nil )
  ( y5           drawing      y5               t t t t nil )
  ( y6           drawing      y6               t t t t nil )
  ( y7           drawing      y7               t t t t nil )
  ( y8           drawing      y8               t t t t nil )
  ( y9           drawing      y9               t t t t nil )
  ( hilite       drawing      hilite           t t t t nil )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t t t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t t t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t t t nil nil )
  ( designFlow   drawing1     designFlow1      t t t nil nil )
  ( designFlow   drawing2     designFlow2      t t t nil nil )
  ( designFlow   drawing3     designFlow3      t t t nil nil )
  ( designFlow   drawing4     designFlow4      t t t nil nil )
  ( designFlow   drawing5     designFlow5      t t t nil nil )
  ( designFlow   drawing6     designFlow6      t t t nil nil )
  ( designFlow   drawing7     designFlow7      t t t nil nil )
  ( designFlow   drawing8     designFlow8      t t t nil nil )
  ( designFlow   drawing9     designFlow9      t t t nil nil )
  ( changedLayer tool0        changedLayerTl0  nil nil t nil nil )
  ( changedLayer tool1        changedLayerTl1  nil nil t nil nil )
  ( marker       warning      markerWarn       t t t t nil )
  ( marker       error        markerErr        t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( Row          label        RowLbl           t nil t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t nil t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
  ( marker       annotate     markerAno        t t t t nil )
  ( marker       info         markerInf        t t t t nil )
  ( marker       ackWarn      markerAck        t t t t nil )
  ( marker       soError      markerSer        t t t t nil )
  ( marker       soCritical   markerScr        t t t t nil )
  ( marker       critical     markerCrt        t t t t nil )
  ( marker       fatal        markerFat        t t t t nil )
  ( snap         boundary     snap             t nil t t nil )
  ( Row          boundary     RowBnd           t t t t nil )
  ( Unrouted     track        UnroutedTrk      t t t t nil )
  ( Group        boundary     GroupBnd         t nil t t nil )
  ( y0           flight       y0Flt            t t t t nil )
  ( y1           flight       y1Flt            t t t t nil )
  ( y2           flight       y2Flt            t t t t nil )
  ( y3           flight       y3Flt            t t t t nil )
  ( y4           flight       y4Flt            t t t t nil )
  ( y5           flight       y5Flt            t t t t nil )
  ( y6           flight       y6Flt            t t t t nil )
  ( y7           flight       y7Flt            t t t t nil )
  ( y8           flight       y8Flt            t t t t nil )
  ( y9           flight       y9Flt            t t t t nil )
  ( border       boundary     area             t nil t t nil )

  ( Nwell        net          nwell            t t nil t nil )
  ( Nwell        subnode      nwell            t t nil t nil )
  ( COMP         net          sldiff           t t nil t nil )
  ( COMP         subnode      sldiff           t t nil t nil )
  ( Poly2        net          polynet          t t nil t nil )
  ( Poly2        subnode      poly             t t nil t nil )
  ( Contact      net          contnet          t t nil t nil )
  ( Contact      subnode      cont             t t nil t nil )
  ( Nplus        net          nplus            t t nil t nil )
  ( Nplus        subnode      nplus            t t nil t nil )
  ( Pplus        net          pplus            t t nil t nil )
  ( Pplus        subnode      pplus            t t nil t nil )
  ( Metal1       net          m1net            t t nil t nil )
  ( Metal1       subnode      m1               t t nil t nil )
  ( Via1         net          v1net            t t nil t nil )
  ( Via1         subnode      v1               t t nil t nil )
  ( Metal2       net          m2net            t t nil t nil )
  ( Metal2       subnode      m2               t t nil t nil )
  ( Via2         net          v2net            t t nil t nil )
  ( Via2         subnode      v2               t t nil t nil )
  ( Metal3       net          m3net            t t nil t nil )
  ( Metal3       subnode      m3               t t nil t nil )
  ( Via3         net          v3net            t t nil t nil )
  ( Via3         subnode      v3               t t nil t nil )
  ( Metal4       net          m4net            t t nil t nil )
  ( Metal4       subnode      m4               t t nil t nil )
  ( Via4         net          v4net            t t nil t nil )
  ( Via4         subnode      v4               t t nil t nil )
  ( Metal5       net          m5               t t nil t nil )
  ( Metal5       subnode      m5               t t nil t nil )
  ( Via5         net          v5net            t t nil t nil )
  ( Via5         subnode      v5               t t nil t nil )
  ( MetalTop     net          m6               t t nil t nil )
  ( MetalTop     subnode      m6               t t nil t nil )

 ) ;techDisplays

 techLayerProperties(
 ;( PropName               Layer1 [ Layer2 ]            PropValue )
 ;( --------               ------ ----------            --------- )
  ( sheetResistance        Metal1                        0.090  )
  ( sheetResistance        Metal2                        0.090  )
  ( sheetResistance        Metal3                        0.090  )
  ( sheetResistance        Metal4                        0.090  )
  ( sheetResistance        Metal5                        0.090  )
  ( sheetResistance        MetalTop                      0.040  )  ; For 9kA and 11kA
 ) ;techLayerProperties

 techDerivedLayers(
 ;( DerivedLayerName          #          composition  )
 ;( ----------------          ------     ------------ )
  ( implants                  10000     ( or  Pplus Nplus ) )
  ( ndiff                     10001     ( and COMP  Nplus) )
  ( pdiff                     10002     ( and COMP  Pplus) )
  ( nChannel                  10003     ( and Poly2 ndiff) )
  ( pChannel                  10004     ( and Poly2 pdiff) )
  ( gate                      10005     ( and COMP  Poly2)  )
  ( po_drw                    10006     ( oaSelect  Poly2 -selectShapesWithPurpose drawing  ))
  ( po_dmy                    10007     ( oaSelect  Poly2 -selectShapesWithPurpose dummy  ))
  ( po_or_dmyPo               10008     ( or  po_drw po_dmy))
  ( co_inside_po              10009     ( and Contact Poly2))
  ( co_inside_diff            10010     ( and Contact COMP))
  ( nstrapdiff                10015     ( and ndiff Nwell ) )
  ( nmosdiff                  10016     ( not ndiff Nwell ) )
  ( pmosdiff                  10017     ( and pdiff Nwell ) )
  ( pstrapdiff                10018     ( not pdiff Nwell ) )
 ) ;techDerivedLayers

) ;layerDefinitions



layerRules(
 equivalentLayers(
 ;( list of layers )
 ;( -------------- )
 ) ;equivalentLayers

 functions(
 ;( layer                       function        [maskNumber])
 ;( -----                         --------              ------------)
  ( Metal1                  "metal"              80)
  ( Via1                      "cut"              85)
  ( Metal2                  "metal"              88)
  ( Via2                      "cut"              91)
  ( Metal3                  "metal"              93)
  ( Via3                      "cut"              94)
  ( Metal4                  "metal"              96)
  ( Via4                      "cut"              97)
  ( Metal5                  "metal"              9E)
  ( Via5                      "cut"              9D)
  ( MetalTop                  "metal"              98)
  ( COMP                  "diffusion"              10)
  ;( AD                       "other"              11)
  ( Nwell                     "nWell"                5)
  ( DNWELL             "nWell"                6)
  ( LVPWELL              "pImplant"                18)
  ;( TP                        "other"                64)
  ;( TN                        "other"                61)
  ( Dualgate                        "other"                38)
  ( Poly2                        "poly"                60)
  ;( MVNVT                        "other"                1L)
  ;( MVPVT                       "other"                2E)
  ( Nplus                    "nImplant"                65)
  ( ESD                     "other"                67)
  ( Pplus                  "pImplant"                70)
  ( Resistor                 "other"                63)
  ( SAB                              "other"                68)
  ( POLYFUSE               "other"                9Z)
  ( Contact               "cut"                75)
  ;( FuseTop             "other"                92)
  ( Pad             "other"                95)
  ;( PIB              "other"                99)
  ;( FuseWindow              "other"                9A)
 ) ;functions


 mfgResolutions(
 ;( layer                       mfgResolution )
 ;( -----                       ------------- )
  ( Metal1                      0.005)
  ( Via1                      0.005)
  ( Metal2                      0.005)
  ( Via2                      0.005)
  ( Metal3                      0.005)
  ( Via3                      0.005)
  ( Metal4                      0.005)
  ( Via4                      0.005)
  ( Metal5                      0.005)
  ( Via5                      0.005)
  ( MetalTop                       0.005)
  ( COMP                      0.005)
  ;( AD                      0.005)
  ( Nwell                      0.005)
  ( DNWELL                      0.005)
  ( LVPWELL                      0.005)
  ;( TP                      0.005)
  ;( TN                      0.005)
  ( Dualgate                      0.005)
  ( Poly2                      0.005)
  ;( MVNVT                       0.005)
  ;( MVPVT                      0.005)
  ( Nplus                       0.005)
  ( ESD                      0.005)
  ( Pplus                       0.005)
  ( Resistor                        0.005)
  ( SAB                        0.005)
  ( POLYFUSE                       0.005)
  ( Contact                       0.005)
 ; ( FuseTop                         0.005)
  ( Pad                      0.005)
 ; ( PIB                       0.005)
  ;( FuseWindow                       0.005)
 ) ;mfgResolutions


 routingDirections(
 ;( layer                       direction     )
 ;( -----                       ---------     )
 ) ;routingDirections


  pinTextLayers(
    ;(  (shape  lpp)      (text  lpp)    (pin  lpp)  )
  ) ;pinTextLayers


 currentDensity(
 ;( rule                    layer1        layer2        value    )
 ;( ----                    ------        ------        -----    )
 ) ;currentDensity


 currentDensityTables(
 ;( rule                    layer1
 ;  (( index1Definitions    [index2Definitions]) [defaultValue] )
 ;  (table))
 ;( ----------------------------------------------------------------------)
 ) ;currentDensityTables


) ;layerRules


viaDefs(
 standardViaDefs(
	; (viaDefName layer1 layer2 (cutLayer cutWidth cutHeight resistancePerCut)
	;  (cutRows cutCol (cutSpace)) (layer1Enc) (layer2Enc)
	;  (layer1Offset) (layer2Offset) (origOffset))

  (polyCont Poly2 Metal1
		("Contact" 0.22 0.22)  ; cutLayer, cutWidth, cutHeight
		(1 1 (0.0 0.0))        ; cutRows, cutCol, cutSpace
		(0.07 0.07)            ; layer1Enc
		(0.06 0.06)            ; layer2Enc
		(0.0 0.0)              ; layer1Offset
		(0.0 0.0)              ; layer2Offset
		(0.0 0.0)              ; origOffset
	)

  (compCont COMP Metal1
		("Contact" 0.22 0.22)  ; cutLayer, cutWidth, cutHeight
		(1 1 (0.0 0.0))        ; cutRows, cutCol, cutSpace
		(0.07 0.07)            ; layer1Enc
		(0.06 0.06)            ; layer2Enc
		(0.0 0.0)              ; layer1Offset
		(0.0 0.0)              ; layer2Offset
		(0.0 0.0)              ; origOffset
	)

	(via12 Metal1 Metal2
		("Via1" 0.26 0.26)  ; cutLayer, cutWidth, cutHeight
		(1 1 (0.0 0.0))     ; cutRows, cutCol, cutSpace
		(0.06 0.06)         ; layer1Enc
		(0.06 0.06)         ; layer2Enc
		(0.0 0.0)           ; layer1Offset
		(0.0 0.0)           ; layer2Offset
		(0.0 0.0)           ; origOffset
	)

	(via23 Metal2 Metal3
		("Via2" 0.26 0.26)  ; cutLayer, cutWidth, cutHeight
		(1 1 (0.0 0.0))     ; cutRows, cutCol, cutSpace
		(0.06 0.06)         ; layer1Enc
		(0.06 0.06)         ; layer2Enc
		(0.0 0.0)           ; layer1Offset
		(0.0 0.0)           ; layer2Offset
		(0.0 0.0)           ; origOffset
	)

	(via34 Metal3 Metal4
		("Via3" 0.26 0.26)  ; cutLayer, cutWidth, cutHeight
		(1 1 (0.0 0.0))     ; cutRows, cutCol, cutSpace
		(0.06 0.06)         ; layer1Enc
		(0.06 0.06)         ; layer2Enc
		(0.0 0.0)           ; layer1Offset
		(0.0 0.0)           ; layer2Offset
		(0.0 0.0)           ; origOffset
	)

	(via45 Metal4 Metal5
		("Via4" 0.26 0.26)  ; cutLayer, cutWidth, cutHeight
		(1 1 (0.0 0.0))     ; cutRows, cutCol, cutSpace
		(0.06 0.06)         ; layer1Enc
		(0.06 0.06)         ; layer2Enc
		(0.0 0.0)           ; layer1Offset
		(0.0 0.0)           ; layer2Offset
		(0.0 0.0)           ; origOffset
	)

	(via5t Metal5 MetalTop
		("Via5" 0.26 0.26)  ; cutLayer, cutWidth, cutHeight
		(1 1 (0.0 0.0))     ; cutRows, cutCol, cutSpace
		(0.06 0.06)         ; layer1Enc
		(0.06 0.06)         ; layer2Enc
		(0.0 0.0)           ; layer1Offset
		(0.0 0.0)           ; layer2Offset
		(0.0 0.0)           ; origOffset
	)
 );standardViaDefs
);viaDefs


;#********************************
;# CONSTRAINT GROUPS
;#********************************
constraintGroups (

 ;( group    [override] )
 ;( -----    ---------- )
  ( "customDesignerDefaultExtractorSetup"    nil
  ) ;customDesignerDefaultExtractorSetup

 ;( group    [override] )
 ;( -----    ---------- )

;;; # leCEConstraintGroup is used for by the Connectivity Engine for signal propagation
; # need to clean up routing vias
  ( leCEConstraintGroup nil
     ( validRoutingLayers (Via5 Via4 Via3 Via2 Via1 Metal5 Metal4 Metal3 Metal2 Metal1 Contact Poly2 COMP))
;    ( validRoutingVias	( via12 via23 via34 via45 polyCont diffCont M4_M5p M3_M4p M2_M3p M1_M2p PO_M1p DIFF_M1p0 NDIFF_M1p PSUBp NWELL_M1p M9_M10p0 M8_M9p0 M7_M8p0 M6_M7p0 M5_M6p0 M4_M5p0 M3_M4p0 M2_M3p0 M1_M2p0 PO_M1p0) )
) ;leCEConstraintGroup

  ( "foundry"    nil
;;; ( constraintGroup Recommended)
     ; # DN-well rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_03.html)
     ( minWidth                   "DNWELL"                    1.7             -comment "dn.1" "dn.1 : Minimum Width of DNWELL 1.7um")
     ( minSpacing                 "DNWELL"                    2.5             -comment "dn.2.a" "dn.2.a : Minimum Spacing of DNWELL equi-potential 2.5um")
     ( minVoltageSpacing          "DNWELL"               (0.0 5.42)           -comment "dn.2.b" "dn.2.b : Minimum Spacing of DNWELL diff-potential 5.42um")

     ; # LVP-well rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_04.html)
     ( minWidth                   "LVPWELL"                   0.6             -comment "lpw.1" "lpw.1 : Minimum Width of LVPWELL 0.6um")
     ( minSpacing                 "LVPWELL"                   0.86            -comment "lpw.2.b" "lpw.2.b : Minimum Spacing of LVPWELL equi-potential 0.86um")
     ( minVoltageSpacing          "LVPWELL"               (0.0 1.4)           -comment "lpw.2.a" "lpw.2.a : Minimum Spacing of LVPWELL diff-potential 1.4um")
     ( minClearance               "LVPWELL"   "DNWELL"        1.5             -comment "lpw.11" "lpw.11 : Min (LVPWELL outside DNWELL) space to DNWELL 1.5um")
     ( minClearance               "LVPWELL"   "Nwell"         0.1             -comment "lpw.12" "lpw.12 : LVPWELL cannot overlap with Nwell")

     ; # N-well rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_05.html)
     ( minWidth                   "Nwell"                    0.86             -comment "nw.1.a" "nw.1.a : Minimum Width of Nwell 0.86um")
     ( minSpacing                 "Nwell"                    0.6              -comment "nw.2.a" "nw.2.a : Minimum Spacing of Nwell equi-potential 0.6um")
     ( minVoltageSpacing          "Nwell"                 (0.0 1.4)           -comment "nw.2.b" "nw.2.b : Minimum Spacing of Nwell diff-potential 1.4um")
     ( minClearance               "Nwell"     "DNWELL"       3.1              -comment "nw.3" "nw.3 : Min. Nwell to DNWELL space 3.1um")
     ( minClearance               "Nwell"     "LVPWELL"      0.0              -comment "nw.4" "nw.4 : Min. Nwell to LVPWELL space 0um")

     ; # Comp (diff) layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_06.html)
     ( minWidth                   "COMP"                     0.22             -comment "df.1.a" "df.1.a : Min. COMP Width 0.22um")
     ( minLength                  "COMP"                     0.22             -comment "df.2.a" "df.2.a : Min. channel width 0.22um")
     ( maxWidth                   "COMP"                     100              -comment "df.2.b" "df.2.b : Max. COMP width for all cases except those used for capacitors, marked by “MOS_CAP_MK” layer 100um")
     ( minSpacing                 "COMP"                     0.28             -comment "df.3.a" "df.3.a : Min. COMP space 0.28um"); # need to somehow include P-substrate tap can be butted for different voltage devices as the potential is same
     ( minSpacing                 "COMP"                     0.32             -comment "df.3.c" "df.3.c : Min. COMP Space in BJT area (area marked by DRC_BJT layer) 0.32um"); # need to mark BJT area somehow
     ( minClearance               "LVPWELL"   "COMP"        0.12             -comment "df.4.a" "df.4.a : Min. (LVPWELL Space to COMP well tap) inside DNWELL 0.12um")
     ( minOverlap                 "DNWELL"    "COMP"        0.62             -comment "df.4.b" "df.4.b : Min. DNWELL overlap of COMP well tap 0.62um")
     ( minOverlap                 "Nwell"     "COMP"        0.43             -comment "df.4.c" "df.4.c : Min. (Nwell overlap of COMP) outside DNWELL 0.43um"); # missing the outside DNWELL
     ( minOverlap                 "Nwell"     "COMP"        0.12             -comment "df.4.d" "df.4.d : Min. (Nwell overlap of COMP) outside DNWELL 0.12um"); # missing the outside DNWELL
     ( minOverlap                 "DNWELL"    "COMP"        0.93             -comment "df.4.e" "df.4.e : Min. DNWELL overlap of COMP 0.93um")
     ( minOverlap                 "LVPWELL"   "COMP"        0.12             -comment "df.5" "df.5 : Min. (LVPWELL overlap of COMP well tap) inside DNWELL 0.12um"); # missing the inside DNWELL
     ( minExtension               "COMP"      "gate"         0.24             -comment "df.6" "df.6 : Min. COMP extend beyond gate (it also means source/drain overhang) 0.24um")
     ( minOverlap                 "LVPWELL"   "COMP"        0.43             -comment "df.8" "df.8 : Min. (LVPWELL overlap of COMP) Inside DNWELL 0.43um"); # missing the inside DNWELL
     ( minArea                    "COMP"                     0.2025           -comment "df.9" "df.9 : Min. COMP area 0.2025 um^2")
     ( maxClearance               "COMP"     "COMP"        20               -comment "df.13" "df.13 : Max distance of Nwell tap (COMP inside Nwell) from (COMP inside Nwell) 20um"); # missing the inside Nwell
     ( maxClearance               "COMP"     "COMP"        20               -comment "df.14" "df.14 : Max distance of substrate tap (COMP outside Nwell) from (COMP outside Nwell) 20um"); # missing outside Nwell, might be fine due to df.13
     ( minClearance               "Nwell"     "COMP"        0.43             -comment "df.16" "df.16 : Min. space from (Nwell outside DNWELL) to (COMP outside Nwell and DNWELL) 0.43um"); # missing outside DNWELL/Nwell
     ( minClearance               "Nwell"     "COMP"        0.12             -comment "df.17" "df.17 : Min. space from (Nwell Outside DNWELL) to (COMP outside Nwell and DNWELL) 0.12um"); # missing outside DNWELL/Nwell
     ( minClearance               "DNWELL"    "COMP"        2.5              -comment "df.18" "df.18 : Min. DNWELL space to (COMP outside Nwell and DNWELL) 2.5um"); # missing outside Nwell/DNWELL
     ( minClearance               "DNWELL"    "COMP"        3.2              -comment "df.19" "df.19 : Min. DNWELL space to (COMP outside Nwell and DNWELL) 3.2um"); # missing outside Nwell/DNWELL

     ; # Poly2 layer Rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_08.html)
     ( minWidth                   "Poly2"                    0.18             -comment "pl.1" "pl.1 : Interconnect Width 0.18um")
     ( maxWidth                   "Poly2"                    0.28             -comment "pl.2" "pl.2 : Gate Width (Channel Length) 0.28um")
     ( minClearance               "Poly2"     "COMP"         0.24             -comment "pl.3.a" "pl.3.a : Space on COMP, Space on Field 0.24um"); # what does "space on" mean, what is "field"
     ( minExtension               "Poly2"     "COMP"         0.22             -comment "pl.4" "pl.4 : Extension beyond COMP to form Poly2 end cap 0.22um")
     ( minClearance               "Poly2"     "COMP"         0.1              -comment "pl.5" "pl.5 : Space from field Poly2 to COMP, Spacer from field Poly2 to Guard-ring 0.1um")
     ( diagonalShapesAllowed      "Poly2"                    false            -comment "pl.6" "pl.6 : 90 deg bends on the COMP are not allowed")
     ( minDiagonalEdgeLength      "Poly2"                    0.3              -comment "pl.7" "pl.7 : 45 deg bent gate width 0.3um")
     ( minDensity                 "Poly2"                    0.14             -comment "pl.8" "pl.8 : Poly2 coverage over the entire die shall be >= 14%")
     ( maxCurrentDensity          "Poly2"                    1                -comment "pl.10" "pl.10 : Maximum Poly2 current density 1 mA/um"); # don't know what the units of maxCurrentDensity are

     ; # Nplus layer Rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_09.html)
     ( minWidth                    "Nplus"                   0.4            -comment "np.1" "np.1 : nplus Minimum Width 0.4u")
     ( minSpacing                  "Nplus"                   0.4            -comment "np.2" "np.2 : nplus Minimum Spacing 0.4u")
     ( minClearance                "Nplus"     "COMP"       0.16           -comment "np.3.a" "np.3.a : Space to COMP 0.16u")
     ( minOverlap                  "Nplus"     "gate"        0.23           -comment "np.5.a" "np.5.a : Overlap of N-channel gate 0.23um"); # need to specify N-channel?
     ( minExtension                "Nplus"     "COMP"        0.16           -comment "np.5.b" "np.5.b : Extension beyond COMP 0.09um")
     ( minArea                     "Nplus"                   0.35           -comment "np.8.a"  "np.8.a : Minimum Area 0.35um2")
     ( minEnclosedArea             "Nplus"                   0.35           -comment "np.8.b"  "np.8.b : Minimum Enclosed area 0.35um2")

     ; # Pplus layer Rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_10.html)
     ( minWidth                    "Pplus"                   0.4            -comment "pp.1" "pp.1 : pplus Minimum Width 0.4u")
     ( minSpacing                  "Pplus"                   0.4            -comment "pp.2" "pp.2 : pplus Minimum Spacing 0.4u")
     ( minClearance                "Pplus"     "COMP"       0.16           -comment "pp.3.a" "pp.3.a : Space to COMP 0.16u")
     ( minOverlap                  "Pplus"     "gate"        0.23           -comment "pp.5.a" "pp.5.a : Overlap of P-channel gate 0.23um"); # need to specify P-channel?
     ( minExtension                "Pplus"     "COMP"        0.16           -comment "pp.5.b" "pp.5.b : Extension beyond COMP 0.09um")
     ( minArea                     "Pplus"                   0.35           -comment "pp.8.a"  "pp.8.a : Minimum Area 0.35um2")
     ( minEnclosedArea             "Pplus"                   0.35           -comment "pp.8.b"  "pp.8.b : Minimum Enclosed area 0.35um2")

     ; # Contact layer Rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_10.html)
     ( minWidth                    "Contact"                 0.22           -comment "co.1" "co.1 : Min/max contact size 0.22um")
     ( maxLength                   "Contact"                 0.22           -comment "co.1" "co.1 : Min/max contact size 0.22um")
     ( minSpacing                  "Contact"                 0.28           -comment "co.2.b" "co.2.b : Space 0.28um")
     ( minOverlap                  "Poly2"     "Contact"     0.07           -comment "co.3" "co.3 : Poly2 overlap of contact 0.07um")
     ( minOverlap                  "COMP"      "Contact"     0.07           -comment "co.4" "co.4 : Poly2 overlap of contact 0.07um")
     ( minOverlap                  "Metal1"    "Contact"     0.005          -comment "co.6" "co.6 : Metal1 overlap of contact 0.005um"); # a couple of extra points listed in the design manual, may need to be included

     ; # Metal 1 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_14.html)
     ( minWidth                    "Metal1"                  0.23           -comment "mn.1" "mn.1 : metal 1 width 0.23um")
     ( minSpacing                  "Metal1"                  0.23           -comment "mn.2.a" "mn.2.a : metal 1 spacing 0.23um")
     ( minSpacing                  "Metal1"        0.23 ((10 0.3))          -comment "mn.2.b" "mn.2.b : space to wide metaln (length & width > 10um) 0.3um")
     ( minArea                     "Metal1"                  0.1444         -comment "mn.3" "mn.3 : Minimum metaln area 0.1444 um^2")
     ( minDensity                  "Metal1"                  0.3            -comment "mn.4" "mn.4 : Metaln coverage over the entire die shall be >30%")

     ; # Metal 2 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_14.html)
     ( minWidth                    "Metal2"                  0.28           -comment "mn.1" "mn.1 : metal 2 width 0.23um")
     ( minSpacing                  "Metal2"                  0.28           -comment "mn.2.a" "mn.2.a : metal 2 spacing 0.23um")
     ( minSpacing                  "Metal2"        0.23 ((10 0.3))          -comment "mn.2.b" "mn.2.b : space to wide metaln (length & width > 10um) 0.3um")
     ( minArea                     "Metal2"                  0.1444         -comment "mn.3" "mn.3 : Minimum metaln area 0.1444 um^2")
     ( minDensity                  "Metal2"                  0.3            -comment "mn.4" "mn.4 : Metaln coverage over the entire die shall be >30%")

     ; # Metal 3 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_14.html)
     ( minWidth                    "Metal3"                  0.28           -comment "mn.1" "mn.1 : metal 3 width 0.23um")
     ( minSpacing                  "Metal3"                  0.28           -comment "mn.2.a" "mn.2.a : metal 3 spacing 0.23um")
     ( minSpacing                  "Metal3"        0.23 ((10 0.3))          -comment "mn.2.b" "mn.2.b : space to wide metaln (length & width > 10um) 0.3um")
     ( minArea                     "Metal3"                  0.1444         -comment "mn.3" "mn.3 : Minimum metaln area 0.1444 um^2")
     ( minDensity                  "Metal3"                  0.3            -comment "mn.4" "mn.4 : Metaln coverage over the entire die shall be >30%")

     ; # Metal 4 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_14.html)
     ( minWidth                    "Metal4"                  0.28           -comment "mn.1" "mn.1 : metal 4 width 0.23um")
     ( minSpacing                  "Metal4"                  0.28           -comment "mn.2.a" "mn.2.a : metal 4 spacing 0.23um")
     ( minSpacing                  "Metal4"        0.23 ((10 0.3))          -comment "mn.2.b" "mn.2.b : space to wide metaln (length & width > 10um) 0.3um")
     ( minArea                     "Metal4"                  0.1444         -comment "mn.3" "mn.3 : Minimum metaln area 0.1444 um^2")
     ( minDensity                  "Metal4"                  0.3            -comment "mn.4" "mn.4 : Metaln coverage over the entire die shall be >30%")

     ; # Metal 5 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_14.html)
     ( minWidth                    "Metal5"                  0.28           -comment "mn.1" "mn.1 : metal 5 width 0.23um")
     ( minSpacing                  "Metal5"                  0.28           -comment "mn.2.a" "mn.2.a : metal 5 spacing 0.23um")
     ( minSpacing                  "Metal5"        0.23 ((10 0.3))          -comment "mn.2.b" "mn.2.b : space to wide metaln (length & width > 10um) 0.3um")
     ( minArea                     "Metal5"                  0.1444         -comment "mn.3" "mn.3 : Minimum metaln area 0.1444 um^2")
     ( minDensity                  "Metal5"                  0.3            -comment "mn.4" "mn.4 : Metaln coverage over the entire die shall be >30%")

     ; # Metal Top layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_16.html)
     ( minWidth                    "MetalTop"                0.36           -comment "mt.1" "mt.1 : metal top width 0.36um")
     ( minSpacing                  "MetalTop"                0.38           -comment "mt.2.a" "mt.2.a : metal top spacing 0.38um")
     ( minSpacing                  "MetalTop"      0.23 ((10 0.5))          -comment "mt.2.b" "mt.2.b : space to wide metaltop (length & width > 10um) 0.5um")
     ( minArea                     "MetalTop"                0.5625         -comment "mt.4" "mn.4 : Minimum metaltop area 0.5625 um^2")
     ( minDensity                  "MetalTop"                0.3            -comment "mt.3" "mn.3 : Metaltop coverage over the entire die shall be >30%")

     ; # Via 1 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_15.html)
     ( minWidth                    "Via1"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( maxLength                   "Via1"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( minSpacing                  "Via1"                    0.26           -comment "vn.2.a" "vn.2.a : Space (1 <= n <= 5) 0.26um")
     ( minAdjacentViaSpacing       "Via1"                    0.36           -numCuts 4 -distance 0.36 -comment "vn.2.b" "vn.2.b : Vian Space in 4x4 or larger Vian array 0.36um")
     ( minClearance                "Metal1"  "Via1"          0.00           -comment "vn.3" "vn.3 : Metaln (where n=1) overlap of Vian 0.00um"); # a couple of extra points listed in the design manual, may need to be included
     ( minOverlap                  "Metal2"  "Via1"          0.01           -comment "vn.4" "vn.4 : Metal [n+1] overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included
     ( viaStackingAllowed          "Via1"    "Via2"          true           -comment "vn.5" "vn.5 : Vian stack (2) over contact is permitted")

     ; # Via 2 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_15.html)
     ( minWidth                    "Via2"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( maxLength                   "Via2"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( minSpacing                  "Via2"                    0.26           -comment "vn.2.a" "vn.2.a : Space (1 <= n <= 5) 0.26um")
     ( minAdjacentViaSpacing       "Via2"                    0.36           -numCuts 4 -distance 0.36 -comment "vn.2.b" "vn.2.b : Vian Space in 4x4 or larger Vian array 0.36um")
     ( minOverlap                  "Metal2"  "Via2"          0.01           -comment "vn.3" "vn.3 : Metaln (where n=2 to 5) overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included
     ( minOverlap                  "Metal3"  "Via2"          0.01           -comment "vn.4" "vn.4 : Metal [n+1] overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included
     ( viaStackingAllowed          "Via2"    "Via3"          true           -comment "vn.5" "vn.5 : Vian stack (2) over contact is permitted")

     ; # Via 3 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_15.html)
     ( minWidth                    "Via3"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( maxLength                   "Via3"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( minSpacing                  "Via3"                    0.26           -comment "vn.2.a" "vn.2.a : Space (1 <= n <= 5) 0.26um")
     ( minAdjacentViaSpacing       "Via3"                    0.36           -numCuts 4 -distance 0.36 -comment "vn.2.b" "vn.2.b : Vian Space in 4x4 or larger Vian array 0.36um")
     ( minOverlap                  "Metal3"  "Via3"          0.01           -comment "vn.3" "vn.3 : Metaln (where n=2 to 5) overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included
     ( minOverlap                  "Metal4"  "Via3"          0.01           -comment "vn.4" "vn.4 : Metal [n+1] overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included
     ( viaStackingAllowed          "Via3"    "Via4"          true           -comment "vn.5" "vn.5 : Vian stack (2) over contact is permitted")

     ; # Via 4 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_15.html)
     ( minWidth                    "Via4"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( maxLength                   "Via4"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( minSpacing                  "Via4"                    0.26           -comment "vn.2.a" "vn.2.a : Space (1 <= n <= 5) 0.26um")
     ( minAdjacentViaSpacing       "Via4"                    0.36           -numCuts 4 -distance 0.36 -comment "vn.2.b" "vn.2.b : Vian Space in 4x4 or larger Vian array 0.36um")
     ( minOverlap                  "Metal4"  "Via4"          0.01           -comment "vn.3" "vn.3 : Metaln (where n=2 to 5) overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included
     ( minOverlap                  "Metal5"  "Via4"          0.01           -comment "vn.4" "vn.4 : Metal [n+1] overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included
     ( viaStackingAllowed          "Via4"    "Via5"          true           -comment "vn.5" "vn.5 : Vian stack (2) over contact is permitted")

     ; # Via 5 layer rules (https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_15.html)
     ( minWidth                    "Via5"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( maxLength                   "Via5"                    0.26           -comment "vn.1" "vn.1 : Min/max via size 0.26um")
     ( minSpacing                  "Via5"                    0.26           -comment "vn.2.a" "vn.2.a : Space (1 <= n <= 5) 0.26um")
     ( minAdjacentViaSpacing       "Via5"                    0.36           -numCuts 4 -distance 0.36 -comment "vn.2.b" "vn.2.b : Vian Space in 4x4 or larger Vian array 0.36um")
     ( minOverlap                  "Metal5"  "Via5"          0.01           -comment "vn.3" "vn.3 : Metaln (where n=2 to 5) overlap of Vian 0.01um"); # a couple of extra points listed in the design manual, may need to be included


    ; # Contact resistance (https://gf180mcu-pdk.readthedocs.io/en/latest/analog/spice/elec_specs/elec_specs_5_2.html)
    electrical(
    ;( constraint        layer1        [layer2]    value  )
    ;( ----------        ------        --------    -----  )
     ( contactRes        "Poly2"                   5.9    ); #no information on 'contactRes' or associated units aside from the sample tech file??
     ( contactRes        "Nplus"                   6.3    )
     ( contactRes        "Pplus"                   5.2    )
     ( contactRes        "Via1"                    4.5    )
     ( contactRes        "Via2"                    4.5    )
     ( contactRes        "Via3"                    4.5    )
     ( contactRes        "Via4"                    4.5    )
     ( contactRes        "Via5"                    4.5    )
    ) ;electrical

    ; # Parasitic capacitance (https://gf180mcu-pdk.readthedocs.io/en/latest/analog/spice/elec_specs/elec_specs_5_6.html)
    orderedElectrical(
    ;( constraint        layer1        layer2        value  )
    ;( ----------        ------        ------        ------ )
;     ( areaCapacitance   "Poly2"       "psub"        111    ); #areaCapacitance or edgeCapacitance? magic tech file uses area
     ( areaCapacitance   "Metal1"      "COMP"        40.2   )
;     ( areaCapacitance   "Metal1"      "psub"        29.5   )
     ( areaCapacitance   "Metal1"      "Poly2"       52.2   )
     ( areaCapacitance   "Metal2"      "Poly2"       16.7   )
     ( areaCapacitance   "Metal2"      "COMP"        15.3   )
;     ( areaCapacitance   "Metal2"      "psub"        13.4   )
     ( areaCapacitance   "Metal2"      "Metal1"      39.4   )
     ( areaCapacitance   "Metal3"      "Metal1"      15.1   )
     ( areaCapacitance   "Metal3"      "Metal2"      39.4   )
     ( areaCapacitance   "Metal4"      "Metal2"      15.1   )
     ( areaCapacitance   "Metal4"      "Metal3"      39.4   )
     ( areaCapacitance   "Metal5"      "Metal3"      15.1   )
     ( areaCapacitance   "Metal5"      "Metal4"      39.4   )
     ( areaCapacitance   "MetalTop"    "Metal4"      15.1   )
     ( areaCapacitance   "MetalTop"    "Metal5"      39.4   )
    ) ;orderedElectrical
  ); foundry

   ( "LEFDefaultRouteSpec"   nil
      ( horizontalRouteGridPitch     Metal1               0.56 )
      ( verticalRouteGridPitch       Metal1               0.56 )
      ( horizontalRouteGridOffset    Metal1               0.00 )
      ( verticalRouteGridOffset      Metal1               0.00 )
      ( minWidth                     Metal1               0.23 )
      ( minWidth                     Via1                 0.26 )

      ( horizontalRouteGridPitch     Metal2               0.56 )
      ( verticalRouteGridPitch       Metal2               0.56 )
      ( horizontalRouteGridOffset    Metal2               0.00 )
      ( verticalRouteGridOffset      Metal2               0.00 )
      ( minWidth                     Metal2               0.28 )
      ( minWidth                     Via2                 0.26 )

      ( horizontalRouteGridPitch     Metal3               0.56 )
      ( verticalRouteGridPitch       Metal3               0.56 )
      ( horizontalRouteGridOffset    Metal3               0.00 )
      ( verticalRouteGridOffset      Metal3               0.00 )
      ( minWidth                     Metal3               0.28 )
      ( minWidth                     Via3                 0.26 )

      ( horizontalRouteGridPitch     Metal4               0.56 )
      ( verticalRouteGridPitch       Metal4               0.56 )
      ( horizontalRouteGridOffset    Metal4               0.00 )
      ( verticalRouteGridOffset      Metal4               0.00 )
      ( minWidth                     Metal4               0.28 )
      ( minWidth                     Via4                 0.26 )

      ( horizontalRouteGridPitch     Metal5               0.56 )
      ( verticalRouteGridPitch       Metal5               0.56 )
      ( horizontalRouteGridOffset    Metal5               0.00 )
      ( verticalRouteGridOffset      Metal5               0.00 )
      ( minWidth                     Metal5               0.28 )
      ( minWidth                     Via5                 0.26 )

      ( horizontalRouteGridPitch     MetalTop             0.90 )
      ( verticalRouteGridPitch       MetalTop             0.90 )
      ( horizontalRouteGridOffset    MetalTop             0.00 )
      ( verticalRouteGridOffset      MetalTop             0.00 )
      ( minWidth                     MetalTop             0.44 )

      ( validRoutingLayers      (Metal1 Metal2 Metal3 Metal4 Metal5 MetalTop)
      )
;      ( validRoutingVias	( via12 via23 via34 via45 via56 via67 via78 via89 via910 polyCont diffCont M9_M10p M8_M9p M7_M8p M6_M7p M5_M6p M4_M5p M3_M4p M2_M3p M1_M2p PO_M1p DIFF_M1p0 NDIFF_M1p PSUBp NWELL_M1p M9_M10p0 M8_M9p0 M7_M8p0 M6_M7p0 M5_M6p0 M4_M5p0 M3_M4p0 M2_M3p0 M1_M2p0 PO_M1p0) )
  );LEFDefaultRouteSpec
) ;constraintGroups




